[package]
name = "zakary/pls-murder"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.5.1"
Comm = "sleitnick/comm@0.3.1"
Trove = "sleitnick/trove@1.0.0"
Component = "sleitnick/component@2.4.6"
Rodux = "roblox/rodux@3.0.0"
Roact = "roblox/roact@1.4.4"
RoactRodux = "roblox/roact-rodux@0.5.1"
ProfileService = "surnautica/profileservice@1.0.0"
Promise = "evaera/promise@4.0.0"
TblUtil = "sleitnick/table-util@1.2.0"